import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __dirname = dirname(fileURLToPath(import.meta.url));

// ESLint 9 flat config. eslint-config-next still ships the legacy shareable
// format, so FlatCompat bridges it.
const compat = new FlatCompat({ baseDirectory: __dirname });

const config = [
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "out/**",
      "build/**",
      "next-env.d.ts",
      // Playwright output (gitignored; generated by npm run test:e2e).
      "playwright-report/**",
      "test-results/**",
      // A gitignored reference Vite app kept for design reference only — it is
      // already excluded from tsconfig for the same reason.
      "Design that I like/**",
      "_archive/**",
      // Claude Code tooling, not project source.
      ".claude/**",
    ],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // HOTFIX 2026-10-09: an effect callback must not return a value. Chrome
    // 140+ returns a Promise from scrollIntoView/scrollTo, and React calls
    // whatever an effect returns as its cleanup, so
    // `useEffect(() => el.scrollIntoView())` crashed the workspace with
    // "destroy is not a function". Use a block body; `() => () => cleanup()`
    // (an effect that only returns its cleanup) is still allowed.
    rules: {
      "no-restricted-syntax": [
        "error",
        {
          selector:
            "CallExpression[callee.name=/^use(Layout|Insertion)?Effect$/] > ArrowFunctionExpression:first-child[body.type!='BlockStatement'][body.type!='ArrowFunctionExpression']",
          message:
            "Give effect callbacks a block body: an expression body returns its value, and React calls a returned non-function (e.g. the Promise Chrome's scrollIntoView returns) as cleanup and crashes.",
        },
      ],
    },
  },
  {
    // Tailwind reads its config through CommonJS, so the plugin import
    // has to stay a require().
    files: ["tailwind.config.ts"],
    rules: { "@typescript-eslint/no-require-imports": "off" },
  },
];

export default config;
